// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
package appservice

import _ "github.com/myeung18/app-operator/pkg/controller/appservice/packrd"
