apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-operator
subjects:
- kind: ServiceAccount
  namespace: {{NAMESPACE}}
  name: app-operator
roleRef:
  kind: ClusterRole
  name: app-operator
  apiGroup: rbac.authorization.k8s.io
